services:
  app:
    hostname: hypertrophy-app
    container_name: hypertrophy-app
    image: python:latest
    restart: unless-stopped
    ports:
      - "8501:8501"  # Map Streamlit's default port
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && streamlit run 01_Current_Workout.py --server.port=8501 --server.address=0.0.0.0"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=CHANGE
      - MYSQL_DATABASE=fitness
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    hostname: hypertrophy-mysql
    container_name: hypertrophy-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: CHANGE
      MYSQL_DATABASE: fitness
    volumes:
      - mysql_data:/var/lib/mysql
      - ./helpers/tables.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init script
    ports:
      - "3601"

volumes:
  mysql_data:
