services:
  app:
    image: python:latest
    container_name: hypertrophy-app
    hostname: hypertrophy-app
    restart: unless-stopped
    ports:
      - 8501  # Map Streamlit's default port
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && streamlit run 01_Current_Workout.py --logger.level=info 2>./server/streamlit/logs.txt"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=fitness
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    hostname: hypertrophy-mysql
    container_name: hypertrophy-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: fitness
    volumes:
      - mysql_data:/var/lib/mysql
      - ./helpers/tables.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init script
    ports:
      - 3601

  nginx:
    image: nginx
    hostname: hypertrophy-nginx
    container_name: hypertrophy-nginx
    restart: unless-stopped
    volumes:
        - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./server/nginx/logs:/var/log/nginx
    ports:
        - 80:80
        - 443:443

volumes:
  mysql_data:
