cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    brandon:
      email: brandon@gmail.com
      failed_login_attempts: 0
      first_name: brandon
      last_name: d
      logged_in: true
      password: $2b$12$gg1wc6akOIrlyfKM/CfG.uQJMTBVI56pvJzWfLJelnjuPQhW9U9ei
      roles:
      - admin
      - editor
      - viewer
    brynlee:
      email: brynlee@gmail.com
      failed_login_attempts: 0
      first_name: brynlee
      last_name: n
      logged_in: true
      password: $2b$12$mxYjluZRe/dxH5VeAkcTaeZfqSeCGMw40sZv60ItQts.y19FAYGcS
      roles:
      - viewer
    david:
      email: david@gmail.com
      failed_login_attempts: 0
      first_name: david
      last_name: c
      logged_in: true
      password: $2b$12$ZLY5rn4IhV.JndEAnfd0IeC9RJPiShxlM/03DX/mpX6BjkYP.IRL2
      roles:
      - viewer
    haden:
      email: haden@gmail.com
      failed_login_attempts: 0
      first_name: haden
      last_name: c
      logged_in: false
      password: $2b$12$mpwVuhRoU8.xyj5yM/3MXe/jqCMS2AojqNoWbUWNNgfhwSA.0eWXe
      roles:
      - viewer
    ivy:
      email: ivy@gmail.com
      failed_login_attempts: 0
      first_name: ivy
      last_name: d
      logged_in: false
      password: $2b$12$O7e0z5hw39Ugxk.qw4pBgelLumc0ax1Dh7l8Bh8VtnRjfLlQE6YBK
      roles:
      - viewer
    spencer:
      email: spenc@gmail.com
      first_name: spencer
      last_name: Ch
      logged_in: false
      password: $2b$12$3odVKvxKCdCCN2jK3Eu3IOpP1wl0ZwqtU8tTvpnYVb1I0ulFCoO8C
      password_hint: Abc
      roles: null
    trevor:
      email: trevor@gmail.com
      failed_login_attempts: 0
      first_name: trevor
      last_name: c
      logged_in: false
      password: $2b$12$otrzyfwDQZajkhNJ3TjrRuh.JFIwKHDmDH.69.jfXsFayp.xxX9Um
      roles:
      - viewer
