cookie:
  expiry_days: 30
  key: some_signature_key # Must be a string
  name: some_cookie_name
credentials:
  usernames:
    brandon:
      email: brandon@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: brandon
      last_name: den
      logged_in: False # Will be managed automatically
      password: abc # Will be hashed automatically
      roles: # Optional
      - admin
      - editor
      - viewer
    trevor:
      email: trevor@gmail.com
      failed_login_attempts: 0
      first_name: trevor
      last_name: ch
      logged_in: False
      password: abc
      roles:
      - viewer
    ivy:
      email: ivy@gmail.com
      failed_login_attempts: 0
      first_name: ivy
      last_name: de
      logged_in: False
      password: abc
      roles:
      - viewer
